export const DEFAULT_PRIMARY_DRAWER_WIDTH = 48;
export const DEFAULT_PRIMARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'default-layout-primary-drawer-width';
export const DEFAULT_PRIMARY_DRAWER_WIDTH_EDITABLE = true;

export const DEFAULT_SECONDARY_DRAWER_WIDTH = 300;
export const DEFAULT_SECONDARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'default-layout-secondary-drawer-width';
export const DEFAULT_SECONDARY_DRAWER_WIDTH_EDITABLE = true;

export const APP_PRIMARY_DRAWER_WIDTH = DEFAULT_PRIMARY_DRAWER_WIDTH;
export const APP_PRIMARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'app-layout-primary-drawer-width';
export const APP_PRIMARY_DRAWER_WIDTH_EDITABLE = true;

export const APP_SECONDARY_DRAWER_WIDTH = DEFAULT_SECONDARY_DRAWER_WIDTH;
export const APP_SECONDARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'app-layout-secondary-drawer-width';
export const APP_SECONDARY_DRAWER_WIDTH_EDITABLE = true;

export const DASHBOARD_PRIMARY_DRAWER_WIDTH = DEFAULT_PRIMARY_DRAWER_WIDTH;
export const DASHBOARD_PRIMARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'dashboard-layout-primary-drawer-width';
export const DASHBOARD_PRIMARY_DRAWER_WIDTH_EDITABLE = true;

export const DASHBOARD_SECONDARY_DRAWER_WIDTH = DEFAULT_SECONDARY_DRAWER_WIDTH;
export const DASHBOARD_SECONDARY_DRAWER_WIDTH_LOCAL_STORAGE_KEY =
  'dashboard-layout-secondary-drawer-width';
export const DASHBOARD_SECONDARY_DRAWER_WIDTH_EDITABLE = true;
